model:
  input_model_data_file: data/example_data/example_void_model.hdf5
  rsd_model: streaming
  z_eff: 0.50
  cosmology:
    Omega_m: 0.31
  realspace_ccf:
    reconstruction: False
    format: multipoles
    ccf_keys: ['r', 'monopole']
  matter_ccf:
    model: template
    integrated: False
    template_keys: ['rdelta', 'delta']
    template_sigma8: 0.628
    bias: 1.9
  velocity_pdf:
    mean:
      model: linear
    dispersion:
      model: template
      template_keys: ['rsv', 'sigmav']
# ---------------------------------------------------- #
